// Clock page — main face with time, date, and next alarm indicator.
#ifndef UNIT_TEST

#include "ui.h"
#include "ui_theme.h"
#include "alarmclock.h"
#include "lvgl.h"
#include <cstdio>

// Large clock font generated by lv_font_conv (160px Montserrat Bold).
LV_FONT_DECLARE(clock_font_160);

namespace alarmclock {

// ---------------------------------------------------------------------------
// Static widgets.
// ---------------------------------------------------------------------------
static lv_obj_t *time_label_ = nullptr;
static lv_obj_t *ampm_label_ = nullptr;
static lv_obj_t *date_label_ = nullptr;
static lv_obj_t *next_alarm_label_ = nullptr;
static lv_obj_t *pre_alarm_label_ = nullptr;

// ---------------------------------------------------------------------------
// Day-of-week names (0=Sunday).
// ---------------------------------------------------------------------------
static const char *kDayNames[] = {
    "Sunday", "Monday", "Tuesday", "Wednesday",
    "Thursday", "Friday", "Saturday"};

static const char *kMonthNames[] = {
    "", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"};

static void nav_alarms_cb(lv_event_t *e) {
  (void)e;
  ui_show_alarm_page();
}

static void nav_settings_cb(lv_event_t *e) {
  (void)e;
  ui_show_settings_page();
}

static lv_obj_t *create_nav_button(lv_obj_t *parent, const char *text,
                                   lv_align_t align, lv_coord_t x,
                                   lv_coord_t y, uint32_t bg_color,
                                   lv_event_cb_t cb) {
  lv_obj_t *btn = lv_button_create(parent);
  lv_obj_set_size(btn, theme::kNavButtonWidth, theme::kNavButtonHeight);
  lv_obj_align(btn, align, x, y);
  lv_obj_set_style_radius(btn, theme::kButtonRadius, 0);
  lv_obj_set_style_bg_color(btn, lv_color_hex(bg_color), 0);
  lv_obj_set_style_border_width(btn, 0, 0);
  lv_obj_add_event_cb(btn, cb, LV_EVENT_CLICKED, nullptr);

  lv_obj_t *label = lv_label_create(btn);
  lv_obj_center(label);
  lv_obj_set_style_text_font(label, &lv_font_montserrat_20, 0);
  lv_obj_set_style_text_color(label, lv_color_hex(theme::kColorPrimary), 0);
  lv_label_set_text(label, text);
  return btn;
}

// ---------------------------------------------------------------------------
// Build the clock page.
// ---------------------------------------------------------------------------
void ui_build_clock_page(lv_obj_t *parent) {
  create_nav_button(parent, "Alarms", LV_ALIGN_TOP_RIGHT, -164, 16,
                    theme::kColorAccent, nav_alarms_cb);
  create_nav_button(parent, "Settings", LV_ALIGN_TOP_RIGHT, -16, 16,
                    0x1F1F1F, nav_settings_cb);

  // Large time label (e.g. "7:00") — digits only, no AM/PM.
  time_label_ = lv_label_create(parent);
  lv_obj_align(time_label_, LV_ALIGN_CENTER, 0, theme::kClockTimeY);
  lv_obj_set_style_text_font(time_label_, &clock_font_160, 0);
  lv_obj_set_style_text_color(time_label_, lv_color_hex(theme::kColorPrimary), 0);
  lv_label_set_text(time_label_, "--:--");

  // AM/PM label — smaller, positioned to the right of the time.
  ampm_label_ = lv_label_create(parent);
  lv_obj_align_to(ampm_label_, time_label_, LV_ALIGN_OUT_RIGHT_BOTTOM, 8, -10);
  lv_obj_set_style_text_font(ampm_label_, &lv_font_montserrat_28, 0);
  lv_obj_set_style_text_color(ampm_label_, lv_color_hex(theme::kColorSecondary), 0);
  lv_label_set_text(ampm_label_, "");

  // Date label (e.g. "Monday, Jan 15").
  date_label_ = lv_label_create(parent);
  lv_obj_align(date_label_, LV_ALIGN_CENTER, 0, theme::kClockDateY);
  lv_obj_set_style_text_font(date_label_, &lv_font_montserrat_40, 0);
  lv_obj_set_style_text_color(date_label_, lv_color_hex(theme::kColorSecondary), 0);
  lv_label_set_text(date_label_, "");

  // Next alarm indicator (e.g. "7:00 AM - Work (in 6h 30m)").
  next_alarm_label_ = lv_label_create(parent);
  lv_obj_align(next_alarm_label_, LV_ALIGN_CENTER, 0, theme::kClockAlarmY);
  lv_obj_set_style_text_font(next_alarm_label_, &lv_font_montserrat_28, 0);
  lv_obj_set_style_text_color(next_alarm_label_, lv_color_hex(theme::kColorAccent), 0);
  lv_label_set_text(next_alarm_label_, "");

  // Pre-alarm banner (e.g. "Alarm in 5 min - Work").
  pre_alarm_label_ = lv_label_create(parent);
  lv_obj_align(pre_alarm_label_, LV_ALIGN_CENTER, 0, theme::kClockPreAlarmY);
  lv_obj_set_style_text_font(pre_alarm_label_, &lv_font_montserrat_28, 0);
  lv_obj_set_style_text_color(pre_alarm_label_, lv_color_hex(theme::kColorSnooze), 0);
  lv_label_set_text(pre_alarm_label_, "");
  lv_obj_add_flag(pre_alarm_label_, LV_OBJ_FLAG_HIDDEN);

}

// ---------------------------------------------------------------------------
// Update functions.
// ---------------------------------------------------------------------------

void ui_update_clock(uint8_t hour, uint8_t minute, bool time_format_24h) {
  if (!time_label_) {
    return;
  }
  char buf[12];
  if (time_format_24h) {
    snprintf(buf, sizeof(buf), "%02d:%02d", hour, minute);
    lv_label_set_text(time_label_, buf);
    if (ampm_label_) {
      lv_label_set_text(ampm_label_, "");
    }
  } else {
    auto [h12, is_pm] = hour_24_to_12(hour);
    snprintf(buf, sizeof(buf), "%d:%02d", h12, minute);
    lv_label_set_text(time_label_, buf);
    if (ampm_label_) {
      lv_label_set_text(ampm_label_, is_pm ? "PM" : "AM");
      lv_obj_align_to(ampm_label_, time_label_, LV_ALIGN_OUT_RIGHT_BOTTOM, 8, -10);
    }
  }
}

void ui_update_date(uint8_t month, uint8_t day, uint8_t day_of_week) {
  if (!date_label_) {
    return;
  }
  if (day_of_week > 6 || month == 0 || month > 12) {
    return;
  }
  char buf[32];
  snprintf(buf, sizeof(buf), "%s, %s %d",
           kDayNames[day_of_week], kMonthNames[month], day);
  lv_label_set_text(date_label_, buf);
}

void ui_update_next_alarm(const char *text) {
  if (!next_alarm_label_) {
    return;
  }
  lv_label_set_text(next_alarm_label_, text ? text : "");
}

void ui_update_pre_alarm_banner(const char *text) {
  if (!pre_alarm_label_) {
    return;
  }
  if (text == nullptr || text[0] == '\0') {
    lv_obj_add_flag(pre_alarm_label_, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(pre_alarm_label_, "");
  } else {
    lv_obj_clear_flag(pre_alarm_label_, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(pre_alarm_label_, text);
  }
}

}  // namespace alarmclock

#endif  // UNIT_TEST
